# Use root/example as user/password credentials
# docker stack deploy -c stack.yml mongo
# docker-compose up
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      AUTH: --auth
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: [--auth]
    restart: always
    
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    restart: always